### ISSUE TITLE
La pantalla en negre de la crossa està torta

### ISSUE THREAD

**Issue by fpraderio** [fpraderio/castelloscopi#7]
La pantall en negre de la crossa, no se si la número 38 o 39, està una mica torta.

Hauria de quedar alineada, mirant des de adalt, amb la pantalla 7

**Comment by fpraderio** [comment]
Molt bé l'inclinació de la 38. 
He vist que en el commit que tanca aquesta issue a76cdf56b963e88aae4e404a3bb282f50ebbfcae has modificat la posició d'altres pantalles, no només de la 38. Com és?

Per altra banda, és millor fer pull requests a devel, i no directament commits a master.

**Comment by PraderioM** [comment]
he tornat a fer els càlculs per veure les posicions que havien d'ocupar el
grup de pantalles del qual la 38 forma part i he considerat que seria
millor modificar-les lleugerament totes per mantindre la simetria.

2016-01-31 18:03 GMT+01:00 Francesco notifications@github.com:
